seed: 42
n_timesteps: 100000000
policy: MlpPolicy
n_steps: 128
n_minibatches: 8
gae_lambda: 0.95
gamma: 0.99
n_epochs: 5
ent_coef: 0.005
learning_rate: 0.0003
clip_range: 0.2
normalize_advantage: true
target_kl: 0.02
vf_coef: 1.0
max_grad_norm: 1.0
normalize_input: true
normalize_value: true
clip_obs: 10.0
policy_kwargs:
  activation_fn: nn.ELU
  net_arch: [512, 512, 256, 128]
  squash_output: false
device: cuda:0
verbose: 1
